### ISSUE TITLE
无法加载字体文件错误，怎么解决？

### ISSUE THREAD

**Issue by hezta** [linyqh/NarratoAI#32]
Traceback (most recent call last):
  File "E:\hezt\NarratoAI\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "E:\Bigmodel\NarratoAI-main\webui\Main.py", line 798, in <module>
    result = tm.start_subclip(task_id=task_id, params=params, subclip_path_videos=st.session_state.subclip_videos)
  File "E:\Bigmodel\NarratoAI-main\app\services\task.py", line 438, in start_subclip
    video.generate_video(video_path=combined_video_path,
  File "E:\Bigmodel\NarratoAI-main\app\services\video.py", line 277, in generate_video
    clip = create_text_clip(subtitle_item=item)
  File "E:\Bigmodel\NarratoAI-main\app\services\video.py", line 237, in create_text_clip
    wrapped_txt, txt_height = wrap_text(
  File "E:\Bigmodel\NarratoAI-main\app\services\video.py", line 147, in wrap_text
    font = ImageFont.truetype(font, fontsize)
  File "E:\hezt\NarratoAI\lib\site-packages\PIL\ImageFont.py", line 807, in truetype
    return freetype(font)
  File "E:\hezt\NarratoAI\lib\site-packages\PIL\ImageFont.py", line 804, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "E:\hezt\NarratoAI\lib\site-packages\PIL\ImageFont.py", line 244, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by linyqh** [comment]
检查目录resource/fonts 是否存在字体文件
正常情况应该是这样的
![image](https://github.com/user-attachments/assets/656d2e50-b63e-4a58-b1b6-85b7fa2cf7d0)
