### ISSUE TITLE
生成脚本失败

### ISSUE THREAD

**Issue by fengyuanluo** [linyqh/NarratoAI#68]
多次运行和不同视频都是同样的报错

`2024-11-30 18:48:48 | INFO | "./app\utils\video_processor_v2.py:272": process_video_pipeline - 步骤1: 压缩视频...
Exception in thread Thread-48 (_readerthread):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "subprocess.py", line 1515, in _readerthread
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 1559: illegal multibyte sequence
2024-11-30 18:49:07 | INFO | "./app\utils\video_processor_v2.py:294": process_video_pipeline -
步骤2: 从压缩视频提取关键帧...
2024-11-30 18:49:07 | INFO | "./app\utils\video_processor_v2.py:219": process_video - 读取视频帧...
读取视频: 100%|██████████████████████████████████████████████████████████████████| 3593/3593 [00:03<00:00, 1068.41it/s]
2024-11-30 18:49:11 | INFO | "./app\utils\video_processor_v2.py:231": process_video - 检测场景边界...
2024-11-30 18:49:17 | INFO | "./app\utils\video_processor_v2.py:233": process_video - 检测到 81 个场景边界
提取关键帧: 100%|██████████████████████████████████████████████████████████████████████| 81/81 [00:07<00:00, 10.87it/s]
保存压缩关键帧: 100%|████████████████████████████████████████████████████████████████| 81/81 [00:00<00:00, 5398.68it/s]
2024-11-30 18:49:26 | INFO | "./app\utils\video_processor_v2.py:299": process_video_pipeline -
步骤3: 提取高清关键帧...
2024-11-30 18:49:26 | ERROR | "./app\utils\video_processor_v2.py:311": process_video_pipeline - 视频处理失败:
Traceback (most recent call last):
  File ".\app\utils\video_processor_v2.py", line 303, in process_video_pipeline
    raise ValueError("未能从压缩视频中提取到有效的关键帧")
ValueError: 未能从压缩视频中提取到有效的关键帧

2024-11-30 18:49:26 | INFO | "./app\utils\video_processor_v2.py:352": process_video_pipeline - 临时文件已清理
2024-11-30 18:49:26 | ERROR | "./webui\components\script_settings.py:674": generate_script - 生成脚本时发生错误
Traceback (most recent call last):
  File ".\webui\components\script_settings.py", line 357, in generate_script
    processor.process_video_pipeline(
  File ".\app\utils\video_processor_v2.py", line 303, in process_video_pipeline
    raise ValueError("未能从压缩视频中提取到有效的关键帧")
ValueError: 未能从压缩视频中提取到有效的关键帧

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\webui\components\script_settings.py", line 389, in generate_script
    raise Exception(f"关键帧提取失败: {str(e)}")
Exception: 关键帧提取失败: 未能从压缩视频中提取到有效的关键帧`

**Comment by linyqh** [comment]
升级新版本
