### ISSUE TITLE
关键帧提取失败: 未能从压缩视频中提取到有效的关键帧

### ISSUE THREAD

**Issue by lestLyy** [linyqh/NarratoAI#72]
2024-12-08 23:30:23 | INFO | "./app\utils\video_processor_v2.py:272": process_video_pipeline - 步骤1: 压缩视频...
2024-12-08 23:30:24 | INFO | "./app\utils\video_processor_v2.py:294": process_video_pipeline -
步骤2: 从压缩视频提取关键帧...
2024-12-08 23:30:24 | INFO | "./app\utils\video_processor_v2.py:219": process_video - 读取视频帧...
读取视频: 100%|███████████████████████████████████████████████████████████████████| 746/746 [00:00<00:00, 10219.22it/s]
2024-12-08 23:30:24 | INFO | "./app\utils\video_processor_v2.py:231": process_video - 检测场景边界...
2024-12-08 23:30:25 | INFO | "./app\utils\video_processor_v2.py:233": process_video - 检测到 0 个场景边界
提取关键帧: 0it [00:00, ?it/s]
保存压缩关键帧: 0it [00:00, ?it/s]
2024-12-08 23:30:25 | INFO | "./app\utils\video_processor_v2.py:299": process_video_pipeline -
步骤3: 提取高清关键帧...
2024-12-08 23:30:25 | ERROR | "./app\utils\video_processor_v2.py:311": process_video_pipeline - 视频处理失败:
Traceback (most recent call last):
  File ".\app\utils\video_processor_v2.py", line 303, in process_video_pipeline
    raise ValueError("未能从压缩视频中提取到有效的关键帧")
ValueError: 未能从压缩视频中提取到有效的关键帧

2024-12-08 23:30:25 | INFO | "./app\utils\video_processor_v2.py:352": process_video_pipeline - 临时文件已清理
2024-12-08 23:30:25 | ERROR | "./webui\components\script_settings.py:674": generate_script - 生成脚本时发生错误
Traceback (most recent call last):
  File ".\webui\components\script_settings.py", line 357, in generate_script
    processor.process_video_pipeline(
  File ".\app\utils\video_processor_v2.py", line 303, in process_video_pipeline
    raise ValueError("未能从压缩视频中提取到有效的关键帧")
ValueError: 未能从压缩视频中提取到有效的关键帧

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\webui\components\script_settings.py", line 389, in generate_script
    raise Exception(f"关键帧提取失败: {str(e)}")
Exception: 关键帧提取失败: 未能从压缩视频中提取到有效的关键帧

**Comment by lestLyy** [comment]
有视频格式要求吗

**Comment by AA25636** [comment]
我也是这样

**Comment by linyqh** [comment]
升级最新版本 0.3.9
