### ISSUE TITLE
生成过程中发生错误: 关键帧提取失败: 未能从压缩视频中提取到有效的关键帧

### ISSUE THREAD

**Issue by bladeww** [linyqh/NarratoAI#82]
2024-12-23 17:12:16 | INFO | "./app\utils\video_processor_v2.py:290": process_video_pipeline - 步骤1: 压缩视频...
Exception in thread Thread-30 (_readerthread):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "subprocess.py", line 1515, in _readerthread
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 1551: illegal multibyte sequence
2024-12-23 17:12:18 | INFO | "./app\utils\video_processor_v2.py:312": process_video_pipeline -
步骤2: 从压缩视频提取关键帧...
2024-12-23 17:12:18 | INFO | "./app\utils\video_processor_v2.py:234": process_video - 读取视频帧...
读取视频: 100%|█████████████████████████████████████████████████████████████████| 3000/3000 [00:00<00:00, 10778.84it/s]
2024-12-23 17:12:18 | INFO | "./app\utils\video_processor_v2.py:246": process_video - 检测场景边界...
2024-12-23 17:12:19 | INFO | "./app\utils\video_processor_v2.py:248": process_video - 检测到 18 个场景边界
提取关键帧: 100%|██████████████████████████████████████████████████████████████████████| 18/18 [00:02<00:00,  6.33it/s]
保存压缩关键帧: 100%|████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 5450.69it/s]
2024-12-23 17:12:22 | INFO | "./app\utils\video_processor_v2.py:317": process_video_pipeline -
步骤3: 提取高清关键帧...
2024-12-23 17:12:22 | ERROR | "./app\utils\video_processor_v2.py:220": extract_numbers_from_folder - 在目录 .\storage\temp\keyframes\b9817c816b8b48e2867be0d6746551a0\temp\mini_frames 中未找到有效的关键帧文件
2024-12-23 17:12:22 | ERROR | "./app\utils\video_processor_v2.py:329": process_video_pipeline - 视频处理失败:
Traceback (most recent call last):

![image](https://github.com/user-attachments/assets/8339c371-ff4c-43bd-9ee1-489bf9e8549a)

**Comment by bladeww** [comment]
有压缩后的视频，log显示保存了压缩关键帧，但是我看并没有保存下来。
已使用管理员模式启动的。

**Comment by xiaoban520** [comment]
> 有压缩后的视频，log显示保存了压缩关键帧，但是我看并没有保存下来。 已使用管理员模式启动的。
你的问题解决了吗

**Comment by xiaoban520** [comment]
这个问题要怎么解决

**Comment by yangshare** [comment]
![image](https://github.com/user-attachments/assets/d4c7360a-0fb5-4b10-a5a9-9fcacdf4e799)
