### ISSUE TITLE
使用短剧混剪功能异常

### ISSUE THREAD

**Issue by blessme** [linyqh/NarratoAI#87]
使用短剧混剪的时候，常常需要把多集内容放在一起，找到高燃镜头。
目前项目只支持单文件，所有我通过剪映把多集内容合并，提取字幕，然后再进行剪辑。

当我点击项目的AI生成短剧混剪脚本时，提示下面错误

生成过程中发生错误: 分析字幕时发生错误：Expecting value: line 1 column 1 (char 0) Traceback (most recent call last): File "step1_subtitle_analyzer_openai.py", line 79, in SDP.utils.step1_subtitle_analyzer_openai.analyze_subtitle File "json_init_.py", line 346, in loads File "json\decoder.py", line 337, in decode File "json\decoder.py", line 355, in raw_decode json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

我的字幕文件如下
[闺蜜对不起-1.txt](https://github.com/user-attachments/files/18271452/-1.txt)

**Comment by cinnik1** [comment]
环球人脉网，人脉即钱脉，欢迎免费注册发帖：http://www.hqrm.cn店连店 注册手机验证就送3元，快乐体验吧： http://www.dld.com
